name: sentinel
on: [push]
jobs:
  sentinel-test:
    runs-on: ubuntu-latest
    container:
      image: thrashr888/sentinel-simulator
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sentinel Test
        run: sentinel test 